survey/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
                       (r'^oswestry/$','survey.views.index'),
                       (r'^neck/$','survey.views.neck'),
                       (r'^thank_you/$','survey.views.thank_you'),
                       )
        

urls.py
# This also imports the include function
from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       (r'^survey/', include('survey.urls')),
                       (r'^admin/', include(admin.site.urls)),
                       )

survey/models.py
from django.db import models
from django import forms

class Survey(models.Model):
    title = models.CharField(max_length=200)
    def __unicode__(self):
        return self.title

class Section(models.Model):
    survey = models.ForeignKey(Survey)
    title = models.CharField(max_length=200)
    def __unicode__(self):
        return self.title

class Question(models.Model):
    section = models.ForeignKey(Section)
    survey = models.ForeignKey(Survey)
    choice = models.CharField(max_length=200)
    def __unicode__(self):
        return self.choice    

class Age(forms.Form):
    AGE_CHOICE = (
        ('lt','less than 60'),
        ('gt','greater than 60')
        )
    AGE = forms.ChoiceField(choices=AGE_CHOICE)    
   
class Procedure(forms.Form):
    PROCEDURE_CHOICES = (
        ('Arthoplasty', 'Arthoplasty'),
        ('Decompression with 1 level fusion', 'Decompression with 1 level fusion'),
        ('Decompression with 2 level fusion', 'Decompression with 2 level fusion'),
        ('Decompression 2 or more levels of fusion', 'Decompression 2 or more levels of fusion'),
        )
    PROCEDURE = forms.ChoiceField(choices=PROCEDURE_CHOICES)

class Status(forms.Form):
    PROCEDURE_CHOICES = (
        ('Preoperative', 'Preoperative'),
        ('4 weeks postop', '4 weeks postop'),
        ('6 weeks postop', 'Decompression with 2 level fusion'),
        ('12 weeks postop', 'Decompression 2 or more levels of fusion'),
        ('6 months postop', 'Decompression 2 or more levels of fusion'),
        ('12 months postop', 'Decompression 2 or more levels of fusion'),                
        )
    STATUS = forms.ChoiceField(choices=PROCEDURE_CHOICES)

survey/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect
from survey.models import Survey, Age, Procedure, Status

def index(request):
    survey=Survey.objects.get(pk=1)
    age=Age()
    procedures=Procedure()
    status=Status()

    sections=survey.section_set.all()
    return render_to_response('survey/oswestry/index.html',
                              {'sections': sections,'age': age,'procedure':procedures,'status':status},
                              context_instance=RequestContext(request))

def thank_you(request):    
    sections=request.POST
    selections=[]
    for s in sections:
        if s != "csrfmiddlewaretoken":
            selections.append(sections[s])
    age=Age(request.POST)
    return render_to_response('survey/thank_you.html',{'data': selections})

def neck(request):
    survey=Survey.objects.get(pk=2)
    age=Age()
    procedures=Procedure()
    status=Status()

    sections=survey.section_set.all()
    return render_to_response('survey/neck/index.html',
                              {'sections': sections,'age': age,'procedure':procedures,'status':status},
                              context_instance=RequestContext(request))

templates/survey/index.html
<form action="/survey/thank_you/" method="post">{% csrf_token %}
<table>
{{ age }}

{{ procedure }}

{{ status }}
</table>

{% for s in sections %}
<h1>{{ s.title }}</h1>
{% for choice in s.choice_set.all %}
    <input type="radio" name="section{{ s.id  }}" id="choice{{ forloop.counter }}" value="{{ choice }}" />
    <label for="choice{{ forloop.counter }}">{{ choice }}</label><br />
{% endfor %}
{% endfor %}

<input type="submit" value="submit" />
</form>
		  

templates/survey/neck/index.html
<form action="/survey/neck/thank_you/" method="post">{% csrf_token %}
<table>
{{ age }}

{{ procedure }}

{{ status }}
</table>

{% for s in sections %}
<h1>{{ s.title }}</h1>
{% for choice in s.question_set.all %}
    <input type="radio" name="section{{ s.id  }}" id="choice{{ forloop.counter }}" value="{{ choice }}" />
    <label for="choice{{ forloop.counter }}">{{ choice }}</label><br />
{% endfor %}
{% endfor %}

<input type="submit" value="submit" />
</form>
		  

templates/survey/neck/thank_you.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title></title>
</head>

<body>
<h1>Thank You</h1>
This will help us to provide better service for you in the future.

{% for d in data %}
<p>{{ d }}</p>
{% endfor %}



</body>
</html>

templates/survey/oswestry/index.html
<form action="/survey/oswestry/thank_you/" method="post">{% csrf_token %}
<table>
{{ age }}

{{ procedure }}

{{ status }}
</table>

{% for s in sections %}
<h1>{{ s.title }}</h1>
{% for choice in s.question_set.all %}
    <input type="radio" name="section{{ s.id  }}" id="choice{{ forloop.counter }}" value="{{ choice }}" />
    <label for="choice{{ forloop.counter }}">{{ choice }}</label><br />
{% endfor %}
{% endfor %}

<input type="submit" value="submit" />
</form>
		  

templates/survey/oswestry/thank_you.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title></title>
</head>

<body>
<h1>Thank You</h1>
This will help us to provide better service for you in the future.

{% for d in data %}
<p>{{ d }}</p>
{% endfor %}



</body>
</html>